# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: External Issue Creation
on:
  repository_dispatch:
    types: ["issue-creation"]

jobs:
  create_issue:
    name: Create Issue
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: write
    steps:
      - name: Create Issue
        uses: actions-ecosystem/action-create-issue@v1
        # uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        with:
          assignees: "jorchiu"
          labels: "Test issue"
          title: "My issue"
          body: |
            ### Hello World Issue

            - [ ] Hello World
                    
            ### Test

            - [HELLO WORLD](https://github.com/orgs/github/projects/3)
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}