name: External Issue Creation
on:
  repository_dispatch:
    types: ["issue-creation"]

env:
  title: ${{ github.event.client_payload.title }}
  body: ${{ github.event.client_payload.body }}
  labels: ${{ github.event.client_payload.labels }}

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions: 
      contents: 'read'
      id-token: 'write'
      issues: 'write'
    steps:
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.github_token }}
          title: ${{env.title}}
          body: |
            ${{ env.body }}
          labels: |
            ${{ env.labels }}